<a href="https://colab.research.google.com/github/Dipta04/Deep-Learning/blob/main/DL_Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report

In [2]:
df = pd.read_csv('healthcare-dataset-stroke-data.csv', na_values=['N/A'])
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [3]:
df.drop(columns=['id'], inplace = True)

In [4]:
df.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [5]:
df.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [6]:
bmi_median = df['bmi'].median()
df['bmi'] = df['bmi'].fillna(bmi_median)

In [7]:
df.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,28.1,never smoked,1
2,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [8]:
df.isnull().sum()

gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [9]:
df.nunique()

gender                  3
age                   104
hypertension            2
heart_disease           2
ever_married            2
work_type               5
Residence_type          2
avg_glucose_level    3979
bmi                   418
smoking_status          4
stroke                  2
dtype: int64

In [10]:
print(df['gender'].unique())

['Male' 'Female' 'Other']

In [11]:
cat_cols = ['gender', 'work_type', 'smoking_status']
binary_cat_cols = ['ever_married', 'Residence_type']

le = LabelEncoder()
for col in binary_cat_cols:
    df[col] = le.fit_transform(df[col])

df = pd.get_dummies(df, columns = cat_cols, dtype = int)
df.head()

,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,stroke,gender_Female,gender_Male,gender_Other,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,67.0,0,1,1,1,228.69,36.6,1,0,1,0,0,0,1,0,0,0,1,0,0
1,61.0,0,0,1,0,202.21,28.1,1,1,0,0,0,0,0,1,0,0,0,1,0
2,80.0,0,1,1,0,105.92,32.5,1,0,1,0,0,0,1,0,0,0,0,1,0
3,49.0,0,0,1,1,171.23,34.4,1,1,0,0,0,0,1,0,0,0,0,0,1
4,79.0,1,0,1,0,174.12,24.0,1,1,0,0,0,0,0,1,0,0,0,1,0

In [12]:
target_col = "stroke"
X = df.drop(columns=[target_col])
y = df[target_col]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

scale_cols = ['age', 'avg_glucose_level', 'bmi']

scaler_sd = StandardScaler()
X_train[scale_cols] = scaler_sd.fit_transform(X_train[scale_cols])
X_test[scale_cols] = scaler_sd.transform(X_test[scale_cols])

In [13]:
X_train_tensor = torch.from_numpy(X_train.values)
X_test_tensor = torch.from_numpy(X_test.values)

X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

y_train_tensor = torch.from_numpy(y_train.values)
y_test_tensor = torch.from_numpy(y_test.values)

y_train_tensor = torch.tensor(y_train_tensor, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

/tmp/ipykernel_725/1648283994.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
/tmp/ipykernel_725/1648283994.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
/tmp/ipykernel_725/1648283994.py:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor, dtype=torch.float32)
/tmp/ipykernel_725/1648283994.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

In [14]:
X_train_tensor.shape[1]

19

## Preprocessing Decisions

1. I remove id feature because it has no importance in model training. Here, I got null values in bmi feature. So I replace the null values with the median value of this feature, which is outlier-resistant.

2. I got binary categorial features like ever_married, Residence_type, where I implement Label encoding and implement one-hot-encoding to other categorial features to convert them into numerical values, which will be helpful in model training.

3. Then I do train test split and implement standard scaling in age, avg_glucose_level, and bmi because this feature got bigger values than other feature which will create bias in the model without scaling.

In [15]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 16),
            nn.ReLU(),
            nn.Linear(16, 8),
            nn.ReLU(),
            nn.Linear(8, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
      out = self.network(features)
      return out

In [16]:
torch.manual_seed(42)
num_features = X_train_tensor.shape[1]
model = Model(num_features)
print(model)

Model(
  (network): Sequential(
    (0): Linear(in_features=19, out_features=16, bias=True)
    (1): ReLU()
    (2): Linear(in_features=16, out_features=8, bias=True)
    (3): ReLU()
    (4): Linear(in_features=8, out_features=1, bias=True)
    (5): Sigmoid()
  )
)

### Explanation:

Input Layer: 18 neurons

Hidden Layer 1: 16 neurons with ReLU activation function

Hidden Layer 2: 8 neurons with ReLU activation function

Output Layer: 1 neuron with Sigmoid function

Here, we use ReLU in hidden layers to avoid vanishing gradients and let the model learn non-linear relationships. And it is a binary classification task which is why we choose Sigmoid for the output.

In [17]:
!pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [18]:
from torchinfo import summary
summary(model, input_size=(X_train_tensor.shape[0], num_features))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [3832, 1]                 --
├─Sequential: 1-1                        [3832, 1]                 --
│    └─Linear: 2-1                       [3832, 16]                320
│    └─ReLU: 2-2                         [3832, 16]                --
│    └─Linear: 2-3                       [3832, 8]                 136
│    └─ReLU: 2-4                         [3832, 8]                 --
│    └─Linear: 2-5                       [3832, 1]                 9
│    └─Sigmoid: 2-6                      [3832, 1]                 --
==========================================================================================
Total params: 465
Trainable params: 465
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 1.78
==========================================================================================
Input size (MB): 0.29
Forward/backward pass size (MB): 0.77
Params size (MB): 0.00
Estimated Total Size (MB): 1.06
==========================================================================================

In [19]:
learning_rate = 0.001
loss_fn = nn.BCELoss()

optimizer = optim.Adam(model.parameters(), lr=learning_rate)

### Justification:

Here I use Binary cross entorphy loss because it is a binary classification task. Adam is a generalized and improved version of plain SGD, which is why I chose this optimizer for my dataset.

In [20]:
epochs = 100

for epoch in range(epochs):
    y_pred = model(X_train_tensor)
    loss = loss_fn(y_pred, y_train_tensor.reshape(-1,1))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1) % 10 == 0:
      print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 10, Loss: 0.7269601225852966
Epoch: 20, Loss: 0.7048525214195251
Epoch: 30, Loss: 0.6777784824371338
Epoch: 40, Loss: 0.6428109407424927
Epoch: 50, Loss: 0.5985395312309265
Epoch: 60, Loss: 0.5455673336982727
Epoch: 70, Loss: 0.4864295721054077
Epoch: 80, Loss: 0.4245096743106842
Epoch: 90, Loss: 0.3637976050376892
Epoch: 100, Loss: 0.3087253272533417

### Pipeline Explanation:

At first, take the learning rate and the epoch number. Run loop on epochs

2. Forward pass
3. Calculate loss
4. Clear old gradients
5. Backward pass
6. Lastly, update weights

In [21]:
with torch.no_grad():
    y_pred = model(X_test_tensor)
    y_pred = (y_pred > 0.3).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.9004386067390442

In [22]:
with torch.no_grad():
    y_pred = model(X_train_tensor)
    y_pred = (y_pred > 0.3).float()
    accuracy = (y_pred == y_train_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.9142577648162842

### Explanation:

Here, we have train data accuracy and the test data accuracy very close. No big difference between the accuracy numbers. So that we can say the model is not underfit or overfit. This model works really well.

In [23]:
epochs = 300

for epoch in range(epochs):
    y_pred = model(X_train_tensor)
    loss = loss_fn(y_pred, y_train_tensor.reshape(-1,1))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1)<=10:
      print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.30368587374687195
Epoch: 2, Loss: 0.29874277114868164
Epoch: 3, Loss: 0.2938987612724304
Epoch: 4, Loss: 0.289155513048172
Epoch: 5, Loss: 0.2845175266265869
Epoch: 6, Loss: 0.27998673915863037
Epoch: 7, Loss: 0.2755647599697113
Epoch: 8, Loss: 0.27125197649002075
Epoch: 9, Loss: 0.2670508325099945
Epoch: 10, Loss: 0.26296356320381165

In [24]:
with torch.no_grad():
    y_pred_update = model(X_test_tensor)
    y_pred_update = (y_pred_update > 0.3).float()
    accuracy = (y_pred_update == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.9374021887779236

### Explanation:

After adding more epochs, we can see that the loss of the model has decreased, and the accuracy is improving. So now we can say the model is making better predictions. But in this dataset, there is a severe class imbalance, and after many epochs, there is a potential risk of overfitting also.

### Questions:

1. Why must gradients be reset every epoch?

2. What happens if learning rate is too high?

3. What happens if learning rate is too small?

4. Why do we define layers inside the constructor (init) and not inside forward()?

Answer 1:

If gradients are not reset in every epoch, then the gradients from the previous epoch add up to the current epoch. As a result, it will give wrong weight updates, and the model will learn incorrectly.

Answer 2:

If the learning rate is too high then the model updates weights too aggresively. In this case, there is a huge possibility model will jump over the optimal solution.

Answer 3:

If the learning rate is too low, then the model update weights too slowly. Thereafter,  the model needs thousands of epochs to experience meaningful improvement.

Answer 4:

If layers are defined in forward(), new weights are created every time whenever the forward pass runs. As a result, model can never learn. On the other hand, If layers are defined inside the constructor (init) then the weights are created once and reuses them in every forward pass so the model learns well.